import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Link } from '@inertiajs/react';
import { Brain, Calculator, Sparkles, TrendingUp, Users } from 'lucide-react';

export default function HomePage({ auth }) {
    const user = auth.user;
    return (
        <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">
            {/* Header */}
            <header className="border-b bg-white/80 backdrop-blur-sm">
                <div className="container mx-auto flex items-center justify-between px-4 py-4">
                    <div className="flex items-center space-x-2">
                        <Sparkles className="h-6 w-6 text-blue-600" />
                        <span className="text-2xl font-bold text-blue-600">QuizAI</span>
                    </div>
                    <div className="flex items-center space-x-4">
                        {user ? (
                            <>
                                <Button asChild>
                                    <Link href="/quizzes/create">New Quiz</Link>
                                </Button>

                                <Button asChild variant="outline">
                                    <Link href="/dashboard">Dashboard</Link>
                                </Button>
                            </>
                        ) : (
                            <>
                                <Button asChild variant="outline">
                                    <Link href="/login">Login</Link>
                                </Button>

                                <Button asChild>
                                    <Link href="/register">Sign Up</Link>
                                </Button>
                            </>
                        )}
                    </div>
                </div>
            </header>

            {/* Hero Section */}
            <section className="container mx-auto px-4 py-20 text-center">
                <div className="mx-auto max-w-4xl">
                    <h1 className="mb-6 text-5xl font-bold text-gray-900">
                        AI-Powered Math Quizzes
                        <span className="text-blue-600"> Tailored for You</span>
                    </h1>
                    <p className="mx-auto mb-8 max-w-2xl text-xl text-gray-600">
                        Generate personalized math quizzes on any topic and difficulty level using DeepSeek V3 AI. Track your progress, learn from
                        explanations, and master mathematics with cutting-edge AI technology.
                    </p>
                    {user ? (
                        <Button asChild size="lg" className="px-8 py-3 text-lg">
                            <Link href="/quizzes/create">Create New Quiz</Link>
                        </Button>
                    ) : (
                        <Button asChild size="lg" className="px-8 py-3 text-lg">
                            <Link href="/register">Start Learning Now</Link>
                        </Button>
                    )}
                </div>
            </section>

            {/* Features */}
            <section className="container mx-auto px-4 py-16">
                <h2 className="mb-12 text-center text-3xl font-bold text-gray-900">Why Choose QuizAI?</h2>
                <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
                    <Card className="text-center">
                        <CardContent className="p-6">
                            <Brain className="mx-auto mb-4 h-12 w-12 text-blue-600" />
                            <h3 className="mb-2 text-xl font-semibold">AI-Generated</h3>
                            <p className="text-gray-600">Unlimited unique questions generated by advanced AI for any math topic</p>
                        </CardContent>
                    </Card>

                    <Card className="text-center">
                        <CardContent className="p-6">
                            <TrendingUp className="mx-auto mb-4 h-12 w-12 text-green-600" />
                            <h3 className="mb-2 text-xl font-semibold">Track Progress</h3>
                            <p className="text-gray-600">Monitor your learning journey with detailed analytics and insights</p>
                        </CardContent>
                    </Card>

                    <Card className="text-center">
                        <CardContent className="p-6">
                            <Calculator className="mx-auto mb-4 h-12 w-12 text-purple-600" />
                            <h3 className="mb-2 text-xl font-semibold">All Topics</h3>
                            <p className="text-gray-600">From basic arithmetic to advanced calculus - we cover it all</p>
                        </CardContent>
                    </Card>

                    <Card className="text-center">
                        <CardContent className="p-6">
                            <Users className="mx-auto mb-4 h-12 w-12 text-orange-600" />
                            <h3 className="mb-2 text-xl font-semibold">Adaptive Learning</h3>
                            <p className="text-gray-600">Difficulty adjusts to your skill level for optimal learning</p>
                        </CardContent>
                    </Card>
                </div>
            </section>

            {/* CTA Section */}
            <section className="bg-blue-600 py-16 text-white">
                <div className="container mx-auto px-4 text-center">
                    <h2 className="mb-4 text-3xl font-bold">Ready to Master Math?</h2>
                    <p className="mb-8 text-xl opacity-90">Join thousands of students improving their math skills with AI</p>
                    {user ? (
                        <Button asChild size="lg" variant="secondary" className="px-8 py-3 text-lg">
                            <Link href="/quizzes/create">Create Your First Quiz</Link>
                        </Button>
                    ) : (
                        <Button asChild size="lg" variant="secondary" className="px-8 py-3 text-lg">
                            <Link href="/register">Create Your Account</Link>
                        </Button>
                    )}
                </div>
            </section>

            {/* Footer */}
            <footer className="bg-gray-900 py-8 text-white">
                <div className="container mx-auto px-4 text-center">
                    <div className="mb-4 flex items-center justify-center space-x-2">
                        <Calculator className="h-6 w-6" />
                        <span className="text-xl font-bold">MathQuiz AI</span>
                    </div>
                    <p className="text-gray-400">© 2024 MathQuiz AI. All rights reserved.</p>
                </div>
            </footer>
        </div>
    );
}
